# Stubs for beancount.core.account_types (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional, NamedTuple, Tuple
from collections import namedtuple

AccountTypes = namedtuple('AccountTypes', 'assets liabilities equity income expenses')
AccountTypes = NamedTuple('AccountTypes', [
    ('assets', str),
    ('liabilities', str),
    ('equity', str),
    ('income', str),
    ('expenses', str),
])
DEFAULT_ACCOUNT_TYPES = ...  # type: AccountTypes

def get_account_sort_key(account_types: AccountTypes, account_name: str) -> Tuple[str, str]: ...
def get_account_type(account_name: str) -> str: ...
def is_root_account(account_name: str, account_types: Optional[str] = ...) -> bool: ...
def is_balance_sheet_account(account_name: str, account_types: AccountTypes) -> bool: ...
def is_income_statement_account(account_name: str, account_types: AccountTypes) -> bool: ...
def is_equity_account(account_name: str, account_types: AccountTypes) -> bool: ...
def get_account_sign(account_name: str, account_types: Optional[AccountTypes] = ...) -> int: ...
