# Stubs for beancount.core.compare (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, NamedTuple, Dict, Set, Tuple, List
from collections import namedtuple

Directive = Any

CompareError = NamedTuple('CompareError', [
    ('source', Dict[str, Any]),
    ('message', str),
    ('entry', Directive),
])
IGNORED_FIELD_NAMES = ...  # type: Set[str]

def stable_hash_namedtuple(objtuple: Directive, ignore: frozenset = ...) -> str: ...
def hash_entry(entry: Directive) -> str: ...
def hash_entries(entries: List[Directive]) -> Tuple[Dict[str, Directive], List[CompareError]]: ...
def compare_entries(entries1: Directive, entries2: Directive) -> Tuple[bool, List[Directive], List[Directive]]: ...
def includes_entries(subset_entries: List[Directive], entries: List[Directive]) -> Tuple[bool, List[Directive]]: ...
def excludes_entries(subset_entries: List[Directive], entries: List[Directive]) -> Tuple[bool, List[Directive]]: ...
