# Stubs for beancount.core.flags (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

FLAG_OKAY = ...  # type: str
FLAG_WARNING = ...  # type: str
FLAG_PADDING = ...  # type: str
FLAG_SUMMARIZE = ...  # type: str
FLAG_TRANSFER = ...  # type: str
FLAG_CONVERSIONS = ...  # type: str
FLAG_UNREALIZED = ...  # type: str
FLAG_RETURNS = ...  # type: str
FLAG_MERGING = ...  # type: str
