# Stubs for beancount.core.number (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def is_fast_decimal(decimal_module): ...

decimal = ...  # type: Any
Decimal = ...  # type: Any
ZERO = ...  # type: Any
HALF = ...  # type: Any
ONE = ...  # type: Any

class MISSING: ...

NUMBER_RE = ...  # type: str

def D(strord: Optional[Any] = ...): ...
def round_to(number, increment): ...
def same_sign(number1, number2): ...
