# Stubs for beancount.core.number (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional, Union
from decimal import Decimal

def is_fast_decimal(decimal_module: Any) -> bool: ...

decimal = ...  # type: Any
Decimal = ...  # type: Callable[[Any], Decimal]
ZERO = ...  # type: Decimal
HALF = ...  # type: Decimal
ONE = ...  # type: Decimal

class MISSING: ...

NUMBER_RE = ...  # type: str

def D(strord: Optional[Union[str, Decimal]] = ...) -> Decimal: ...
def round_to(number: Decimal, increment: Decimal) -> Decimal: ...
def same_sign(number1: Decimal, number2: Decimal) -> bool: ...
