# Stubs for beancount.parser.booking (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import NamedTuple, Dict, Any, List, Tuple
from beancount.core.data import Booking

METADATA = Dict[str, Any]
Directive = Any

BookingError = NamedTuple('BookingError', [
    ('source', METADATA),
    ('message', str),
    ('entry', Directive),
])

def book(incomplete_entries: List[Directive], options_map: Dict[str, Any]) -> Tuple[List[Directive], List[BookingError]]: ...
def validate_missing_eliminated(entries: List[Directive], unused_options_map: Dict[str, Any]) -> List[BookingError]: ...
def validate_inventory_booking(entries: List[Directive], unused_options_map: Dict[str, Any], booking_methods: Dict[str, Booking]) -> List[BookingError]: ...
